export const VALIDATION_SUCCESSFUL = "VALIDATION_SUCCESSFUL";
export const VALIDATION_FAILURE = "VALIDATION_FAILURE";
export const VALIDATION_USERFOUND = "VALIDATION_USERFOUND";
export const VALIDATION_USERNOTFOUND = "VALIDATION_USERNOTFOUND";
export const PASSWORD_UPDATION_SUCCESSFUL = "PASSWORD_UPDATION_SUCCESSFUL";
export const PASSWORD_UPDATION_FAILURE = "PASSWORD_UPDATION_FAILURE";
